spring:
 datasource:
   url: jdbc:mysql://gz-cdb-15rtzmkc.sql.tencentcdb.com:62650/bug_manager?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true
   username: root
   password: Xiong19950823
   driver-class-name: com.mysql.jdbc.Driver
   platform: mysql
   type: com.alibaba.druid.pool.DruidDataSource
   # 下面为连接池的补充设置，应用到上面所有数据源中
   # 初始化大小，最小，最大
   initialSize: 1
   minIdle: 3
   maxActive: 100
   # 配置获取连接等待超时的时间
   maxWait: 60000
   # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
   timeBetweenEvictionRunsMillis: 60000
   # 配置一个连接在池中最小生存的时间，单位是毫秒
   minEvictableIdleTimeMillis: 30000
   validationQuery: select 'x'
   testWhileIdle: true
   testOnBorrow: false
   testOnReturn: false
   # 打开PSCache，并且指定每个连接上PSCache的大小
   poolPreparedStatements: true
   maxPoolPreparedStatementPerConnectionSize: 20
   # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
   filters: stat,wall,slf4j
   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
   connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


#公共配置与profiles选择无关
 profiles:
     active: dev


#邮箱设置

 mail:
    host: smtp.qq.com
    username: 425277456@qq.com   # 这里填写个人的qq邮箱
    password: ifokwdcuacpqbjic # 注：这里不是qq邮箱的密码，而是授权码
    port: 25
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true



 rabbitmq:
    host: 119.29.137.14
    port: 5672
    username: xiongcp
    password: xiongchengpeng
    virtual-host: /
    publisher-confirms: true
    mq:
      exchange: email_exchange
      routekey: email_routekey


mybatis:
  typeAliasesPackage: com.rabbit.xiongcp.consumer.entity
  mapper-locations: classpath*:/mapping/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


server:
  port: 8088
logging:
  level:
    com.xiongcp.bug.manager.dao: DEBUG



thread:
  corePoolSize: 10
  maxPoolSize: 1000
  queueCapacity: 8
  keepAlive: 60

